[project]
name = "forest-fire"
version = "0.1.0"
description = ""
requires-python = ">=3.10"
dependencies = [
    "dash>=3.0.4",
    "noise>=1.2.2",
    "numpy>=2.2.4",
    "plotly>=6.0.1",
    "scipy>=1.15.2",
    "simcx",
]
